version: 0.2

env:
  secrets-manager:
    TASKCAT_SECRET: NT48-lab2

phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - echo "Installing cfn-lint and taskcat"
      - pip install cfn-lint taskcat
      - yum install -y jq curl

  pre_build:
    commands:
      - echo "Fetching secret values from Secrets Manager"
      - |
        SECRET_JSON=$(aws secretsmanager get-secret-value \
        --region ${AWS_REGION} \
        --secret-id "$TASKCAT_SECRET" \
        --query SecretString \
        --output text)

        export REGION=$(echo "$SECRET_JSON" | jq -r '.REGION')
        export S3_BUCKET=$(echo "$SECRET_JSON" | jq -r '.S3_BUCKET')
        export KEY_NAME=$(echo "$SECRET_JSON" | jq -r '.KEY_NAME')
        export AMI_ID=$(echo "$SECRET_JSON" | jq -r '.AMI_ID')

        export AVAILABILITY_ZONE=$(aws ec2 describe-availability-zones \
          --region "$REGION" \
          --query "AvailabilityZones[0].ZoneName" \
          --output text)

        export ALLOWED_SSH_IP="$(curl -s http://checkip.amazonaws.com)/32"

        echo "REGION=$REGION"
        echo "S3_BUCKET=$S3_BUCKET"
        echo "KEY_NAME=$KEY_NAME"
        echo "AMI_ID=$AMI_ID"
        echo "AVAILABILITY_ZONE=$AVAILABILITY_ZONE"
        echo "ALLOWED_SSH_IP=$ALLOWED_SSH_IP"

        echo "Generating final .taskcat.yml file..."
        envsubst < taskcat.template.yml > .taskcat.yml

      - echo "Validating CloudFormation templates"
      - cfn-lint CloudFormation/**/*.yaml

  build:
    commands:
      - echo "Running taskcat test"
      - taskcat test run
