version: 0.2

env:
  secrets-manager:
    REGION: "NT548-lab2:REGION"
    S3_BUCKET: "NT548-lab2:S3_BUCKET"
    KEY_NAME: "NT548-lab2:KEY_NAME"
    AMI_ID: "NT548-lab2:AMI_ID"

phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - echo "Installing cfn-lint and taskcat"
      - pip install cfn-lint taskcat
      - yum install -y jq

  pre_build:
    commands:
      - echo "Fetching secret values from Secrets Manager"
      - |
        # Parse JSON và export variables
        export REGION=$REGION
        export S3_BUCKET=$S3_BUCKET
        export KEY_NAME=$KEY_NAME
        export AMI_ID=$AMI_ID

        # Lấy availability zone đầu tiên của region
        export AVAILABILITY_ZONE=$(aws ec2 describe-availability-zones \
          --region "$REGION" \
          --query "AvailabilityZones[0].ZoneName" \
          --output text)

        # Lấy IP hiện tại của CodeBuild
        export ALLOWED_SSH_IP="$(curl -s http://checkip.amazonaws.com)/32"

        echo "Configuration:"
        echo "REGION=$REGION"
        echo "S3_BUCKET=$S3_BUCKET"
        echo "KEY_NAME=$KEY_NAME"
        echo "AMI_ID=$AMI_ID"
        echo "AVAILABILITY_ZONE=$AVAILABILITY_ZONE"
        echo "ALLOWED_SSH_IP=$ALLOWED_SSH_IP"

        # Tạo .taskcat.yml từ template
        echo "Generating final .taskcat.yml file..."
        envsubst < taskcat.template.yml > .taskcat.yml

        echo "Generated .taskcat.yml:"
        cat .taskcat.yml

      - echo "Validating CloudFormation templates"
      - cfn-lint CloudFormation/**/*.yaml

  build:
    commands:
      - echo "Running taskcat test"
      - taskcat test run

  post_build:
    commands:
      - echo "TaskCat test completed"
