version: 0.2

env:
  secrets-manager:
    REGION: REGION
    S3_BUCKET: S3_BUCKET
    KEY_NAME: KEY_NAME
    AMI_ID: AMI_ID
    AVAILABILITY_ZONE: AVAILABILITY_ZONE

phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - echo "Installing cfn-lint and taskcat"
      - pip install cfn-lint taskcat
      - yum install -y jq

  pre_build:
    commands:
      - echo "Fetching secret values from Secrets Manager and exporting them"
      - export REGION=$REGION
      - export S3_BUCKET=$S3_BUCKET
      - export KEY_NAME=$KEY_NAME
      - export AMI_ID=$AMI_ID
      - export AVAILABILITY_ZONE=$AVAILABILITY_ZONE
      - export ALLOWED_SSH_IP="$(curl -s http://checkip.amazonaws.com)/32"

      - echo "Writing params.json..."
      - |
        cat <<EOF > params.json
        {
          "Parameters": {
            "AvailabilityZone": "$AVAILABILITY_ZONE",
            "AllowedSSHIp": "$ALLOWED_SSH_IP",
            "AMI": "$AMI_ID",
            "KeyName": "$KEY_NAME",
            "BucketName": "$S3_BUCKET"
          }
        }
        EOF

      - echo "Generating final .taskcat.yml file..."
      - envsubst < taskcat.template.yml > .taskcat.yml
      - echo "Generated .taskcat.yml content:"
      - cat .taskcat.yml

      - echo "Validating CloudFormation templates..."
      - cfn-lint CloudFormation/**/*.yaml

  build:
    commands:
      - echo "Running taskcat tests..."
      - taskcat test run -d

  post_build:
    commands:
      - echo "TaskCat test completed."

artifacts:
  files:
    - params.json
