version: 0.2

env:
  secrets-manager:
    REGION: "{{resolve:secretsmanager:REGION:SecretString}}"
    S3_BUCKET: "{{resolve:secretsmanager:S3_BUCKET:SecretString}}"
    KEY_NAME: "{{resolve:secretsmanager:KEY_NAME:SecretString}}"
    AMI_ID: "{{resolve:secretsmanager:AMI_ID:SecretString}}"
    AVAILABILITY_ZONE: "{{resolve:secretsmanager:AVAILABILITY_ZONE:SecretString}}"

phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - echo "Installing cfn-lint and taskcat"
      - pip install cfn-lint taskcat
      - yum install -y jq

  pre_build:
    commands:
      - echo "Fetching secret values from Secrets Manager"
      - |
        # Parse JSON và export variables
        export REGION=$REGION
        export KEY_NAME=$KEY_NAME
        export AMI_ID=$AMI_ID
        export AVAILABILITY_ZONE=$AVAILABILITY_ZONE

        # Lấy IP hiện tại của CodeBuild
        export ALLOWED_SSH_IP="$(curl -s http://checkip.amazonaws.com)/32"

        echo "Configuration:"
        echo "REGION=$REGION"
        echo "KEY_NAME=$KEY_NAME"
        echo "AMI_ID=$AMI_ID"
        echo "AVAILABILITY_ZONE=$AVAILABILITY_ZONE"
        echo "ALLOWED_SSH_IP=$ALLOWED_SSH_IP"

        # Tạo .taskcat.yml từ template
        echo "Generating final .taskcat.yml file..."
        envsubst < taskcat.template.yml > .taskcat.yml

        echo "Generated .taskcat.yml:"
      - taskcat test run --exit-on-failure --no-delete --keep-failed -d
      - echo "Validating CloudFormation templates"
      - cfn-lint CloudFormation/**/*.yaml

  build:
    commands:
      - echo "Running taskcat test"
      - taskcat test run -d

  post_build:
    commands:
      - echo "TaskCat test completed"
