AWSTemplateFormatVersion: "2010-09-09"
Description: "Internet Gateway Module"

Parameters:
  VpcId:
    Type: String
    Description: The ID of the VPC

  Name:
    Type: String
    Description: Name tag for the Internet Gateway
    Default: "my-igw"

Resources:
  InternetGateway:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
        - Key: Name
          Value: !Ref Name

  AttachGateway:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId: !Ref VpcId
      InternetGatewayId: !Ref InternetGateway

Outputs:
  InternetGatewayId:
    Description: ID of the created Internet Gateway
    Value: !Ref InternetGateway
    Export:
      Name: !Sub ${AWS::StackName}-IgwId
