AWSTemplateFormatVersion: "2010-09-09"
Description: "NAT Gateway Module"

Parameters:
  PublicSubnetID:
    Type: String
    Description: "ID of the public subnet"

Resources:
  ElasticIP:
    Type: AWS::EC2::EIP
    Properties:
      Domain: vpc

  NATGateway:
    Type: AWS::EC2::NatGateway
    Properties:
      AllocationId: !GetAtt ElasticIP.AllocationId
      SubnetId: !Ref PublicSubnetID

Outputs:
  NATGatewayID:
    Description: ID of the created NAT Gateway
    Value: !Ref NATGateway
    Export:
      Name: !Sub ${AWS::StackName}-NATGateway
