AWSTemplateFormatVersion: "2010-09-09"
Description: "EC2 Instance"

Parameters:
  VpcId:
    Type: String
    Description: "VPC ID for the security group"

  AllowedSSHIp:
    Type: String
    Description: "CIDR block for allowed SSH access"

Resources:
  SecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      VpcId: !Ref VpcId
      GroupName: "public-sg"
      GroupDescription: "Security group for public instances" # Added required description
      SecurityGroupIngress:
        - CidrIp: !Ref AllowedSSHIp
          FromPort: 22
          IpProtocol: tcp
          ToPort: 22

      SecurityGroupEgress:
        - IpProtocol: "-1"
          CidrIp: 0.0.0.0/0

      Tags:
        - Key: Name
          Value: public-sg

Outputs:
  PublicSGId:
    Value: !Ref SecurityGroup
